var gl_sat = {
 "Abbaye" :  [{"n" : "Cheese", "e" : 35, "c" : 20}],
 "Almond" :  [{"n" : "Nuts & Seeds", "e" : 15, "c" : 15}],
 "Ant Empress" :  [{"n" : "Creepies & Crawlies", "e" : 20, "c" : 20}],
 "Ant Larvae" :  [{"n" : "Creepies & Crawlies", "e" : 30, "c" : 5}],
 "Ant Pupae" :  [{"n" : "Creepies & Crawlies", "e" : 10, "c" : 80}],
 "Ant Queen" :  [{"n" : "Creepies & Crawlies", "e" : 20, "c" : 20}],
 "Ant Soldiers" :  [{"n" : "Creepies & Crawlies", "e" : 10, "c" : 20}],
 "Aphids" :  [{"n" : "Forage", "e" : 20, "c" : 10}],
 "Apple Pie" :  [{"n" : "Fruit", "e" : 30, "c" : 30}, {"n" : "Bread", "e" : 15, "c" : 20}],
 "Autumn Steak" :  [{"n" : "Mushrooms", "e" : 34, "c" : 25}, {"n" : "Meat", "e" : 15, "c" : 20}],
 "Badger Botillo" :  [{"n" : "Meat", "e" : 45, "c" : 20}],
 "Baked Birchbark Bream" :  [{"n" : "Fish", "e" : 30, "c" : 30}],
 "Banon" :  [{"n" : "Cheese", "e" : 36, "c" : 25}],
 "Bark Bread" :  [{"n" : "Bread", "e" : 35, "c" : 32}],
 "Bay Bolete" :  [{"n" : "Mushrooms", "e" : 5, "c" : 50}],
 "Bear Salami" :  [{"n" : "Sausage", "e" : 40, "c" : 20}],
 "Beaver Delights" :  [{"n" : "Forage", "e" : 40, "c" : 10}],
 "Beaver Dog" :  [{"n" : "Sausage", "e" : 30, "c" : 30}],
 "Bee Larvae" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 10}],
 "Beech Nuts" :  [{"n" : "Nuts & Seeds", "e" : 10, "c" : 25}],
 "Beeted Bird Breast" :  [{"n" : "Fowl & Poultry", "e" : 36, "c" : 25}, {"n" : "Vegetables", "e" : 20, "c" : 15}],
 "Beetroot" :  [{"n" : "Vegetables", "e" : 20, "c" : 25}],
 "Beetroot Leaves" :  [],
 "Big Bear Banger" :  [{"n" : "Sausage", "e" : 40, "c" : 20}, {"n" : "Meat", "e" : 25, "c" : 16}],
 "Birchbark Bream" :  [{"n" : "Fish", "e" : 30, "c" : 30}],
 "Birthday Cake" :  [{"n" : "Sweets & Desserts", "e" : 35, "c" : 20}],
 "Black Ribeye Steak" :  [{"n" : "Meat", "e" : 30, "c" : 30}],
 "Black Trumpets" :  [{"n" : "Forage", "e" : 15, "c" : 15}],
 "Blackberry" :  [{"n" : "Berries", "e" : 20, "c" : 5}],
 "Blackcurrant" :  [{"n" : "Berries", "e" : 10, "c" : 10}],
 "Bloated Bolete" :  [{"n" : "Mushrooms", "e" : 40, "c" : 5}],
 "Blubber Feast" :  [{"n" : "Meat", "e" : 35, "c" : 20}],
 "Blueberries" :  [{"n" : "Forage", "e" : 30, "c" : 5}],
 "Blueberry Pie" :  [{"n" : "Berries", "e" : 40, "c" : 20}, {"n" : "Sweets & Desserts", "e" : 30, "c" : 20}],
 "Boar Baloney" :  [{"n" : "Sausage", "e" : 30, "c" : 30}],
 "Boar Boudin" :  [{"n" : "Sausage", "e" : 40, "c" : 20}],
 "Boiled Egg" :  [{"n" : "Fowl & Poultry", "e" : 5, "c" : 70}],
 "Boiled Gooseneck Barnacle" :  [{"n" : "Fish", "e" : 20, "c" : 10}, {"n" : "Forage", "e" : 20, "c" : 5}],
 "Boiled Lobster" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Boiled Razor Clam" :  [{"n" : "Fish", "e" : 15, "c" : 15}],
 "Boiled River Pearl Mussel" :  [{"n" : "Fish", "e" : 20, "c" : 10}, {"n" : "Forage", "e" : 20, "c" : 5}],
 "Bone Marrow" :  [{"n" : "Offal", "e" : 20, "c" : 20}],
 "Bread" :  [{"n" : "Bread", "e" : 40, "c" : 20}],
 "Brique" :  [{"n" : "Cheese", "e" : 35, "c" : 25}],
 "Brodgar Blue Cheese" :  [{"n" : "Cheese", "e" : 25, "c" : 30}],
 "Broiled Burbot" :  [{"n" : "Fish", "e" : 20, "c" : 30}],
 "Bucheron" :  [{"n" : "Cheese", "e" : 24, "c" : 25}],
 "Butcher's Surprise" :  [{"n" : "Sausage", "e" : 30, "c" : 30}],
 "Butter Porridge" :  [{"n" : "Dairy", "e" : 30, "c" : 20}],
 "Butter Scones" :  [{"n" : "Bread", "e" : 15, "c" : 50}, {"n" : "Dairy", "e" : 20, "c" : 10}],
 "Butter-Chived Trout" :  [{"n" : "Fish", "e" : 30, "c" : 20}, {"n" : "Dairy", "e" : 20, "c" : 10}],
 "Butter-steamed Cavebulb" :  [{"n" : "Vegetables", "e" : 15, "c" : 15}, {"n" : "Dairy", "e" : 30, "c" : 10}],
 "Buttered Leeks" :  [{"n" : "Vegetables", "e" : 35, "c" : 25}],
 "Cabrales" :  [{"n" : "Cheese", "e" : 28, "c" : 25}],
 "Caciotta" :  [{"n" : "Cheese", "e" : 25, "c" : 36}],
 "Camomile" :  [{"n" : "Forage", "e" : 10, "c" : 15}],
 "Candleberry" :  [{"n" : "Berries", "e" : 20, "c" : 15}],
 "Candy Apple" :  [{"n" : "Sweets & Desserts", "e" : 30, "c" : 20}],
 "Carrot" :  [{"n" : "Vegetables", "e" : 20, "c" : 20}],
 "Carrot Cake" :  [{"n" : "Sweets & Desserts", "e" : 30, "c" : 30}],
 "Cattail Roots" :  [{"n" : "Forage", "e" : 5, "c" : 40}],
 "Cave Cheddar" :  [{"n" : "Cheese", "e" : 30, "c" : 25}],
 "Cave Louse Leg" :  [{"n" : "Creepies & Crawlies", "e" : 20, "c" : 35}],
 "Cave Skewer" :  [{"n" : "Creepies & Crawlies", "e" : 35, "c" : 20}, {"n" : "Creepies & Crawlies", "e" : 16, "c" : 20}],
 "Cave Slime" :  [{"n" : "Creepies & Crawlies", "e" : 25, "c" : 40}],
 "Cavebulb" :  [{"n" : "Vegetables", "e" : 10, "c" : 10}, {"n" : "Forage", "e" : 10, "c" : 10}],
 "Cavedog" :  [{"n" : "Forage", "e" : 34, "c" : 25}],
 "Cellar Cheddar" :  [{"n" : "Cheese", "e" : 25, "c" : 25}],
 "Centibab" :  [{"n" : "Creepies & Crawlies", "e" : 40, "c" : 10}],
 "Chabichou" :  [{"n" : "Cheese", "e" : 30, "c" : 30}],
 "Chabis" :  [{"n" : "Cheese", "e" : 40, "c" : 20}],
 "Chantrelles" :  [{"n" : "Mushrooms", "e" : 10, "c" : 20}],
 "Cheesecake" :  [{"n" : "Cheese", "e" : 40, "c" : 20}, {"n" : "Sweets & Desserts", "e" : 20, "c" : 15}],
 "Cherries" :  [{"n" : "Fowl & Poultry", "e" : 25, "c" : 6}],
 "Chestnut" :  [{"n" : "Nuts & Seeds", "e" : 15, "c" : 10}],
 "Chewy Chevon" :  [{"n" : "Meat", "e" : 10, "c" : 25}],
 "Chicken Chorizo" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 25}, {"n" : "Sausage", "e" : 25, "c" : 16}],
 "Chicken Salad" :  [{"n" : "Fowl & Poultry", "e" : 25, "c" : 32}, {"n" : "Vegetables", "e" : 40, "c" : 5}],
 "Chives" :  [{"n" : "Vegetables", "e" : 7, "c" : 20}],
 "Clambake" :  [{"n" : "Fish", "e" : 25, "c" : 30}],
 "Cone Gruel" :  [{"n" : "Nuts & Seeds", "e" : 20, "c" : 25}],
 "Cornucopia" :  [{"n" : "Bread", "e" : 30, "c" : 20}, {"n" : "Fruit", "e" : 15, "c" : 40}, {"n" : "Vegetables", "e" : 40, "c" : 15}],
 "Cow Chorizo" :  [{"n" : "Meat", "e" : 32, "c" : 35}, {"n" : "Dairy", "e" : 20, "c" : 20}],
 "Cow's Curd" :  [{"n" : "Dairy", "e" : 30, "c" : 20}],
 "Crab Cakes" :  [{"n" : "Fish", "e" : 35, "c" : 20}, {"n" : "Vegetables", "e" : 15, "c" : 20}],
 "Crab Roe" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Creamy Camembert" :  [{"n" : "Cheese", "e" : 40, "c" : 20}],
 "Creamy Cock" :  [{"n" : "Dairy", "e" : 40, "c" : 20}, {"n" : "Fowl & Poultry", "e" : 20, "c" : 20}],
 "Crêpe Citrouille" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}, {"n" : "Dairy", "e" : 25, "c" : 16}],
 "Crêpe Noisette" :  [{"n" : "Nuts & Seeds", "e" : 40, "c" : 19}, {"n" : "Dairy", "e" : 20, "c" : 10}],
 "Cucumber" :  [{"n" : "Vegetables", "e" : 40, "c" : 10}],
 "Cucumber Salsa" :  [{"n" : "Vegetables", "e" : 40, "c" : 20}],
 "Curd'n'Chives" :  [{"n" : "Dairy", "e" : 20, "c" : 35}],
 "Deep Fried Bird" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 35}],
 "Delicious Deer Dog" :  [{"n" : "Game", "e" : 20, "c" : 35}, {"n" : "Sausage", "e" : 25, "c" : 20}],
 "Dog Rose Hips" :  [{"n" : "Berries", "e" : 20, "c" : 8}],
 "Dream Cookies" :  [{"n" : "Sweets & Desserts", "e" : 50, "c" : 10}],
 "Dressed Lettuce" :  [{"n" : "Vegetables", "e" : 40, "c" : 20}],
 "Dried Batwings" :  [{"n" : "Meat", "e" : 30, "c" : 20}],
 "Dried Filet of Abyss Gazer" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Dried Filet of Asp" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Dried Filet of Bass" :  [{"n" : "Fish", "e" : 15, "c" : 13}],
 "Dried Filet of Bream" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Dried Filet of Brill" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Dried Filet of Burbot" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Dried Filet of Carp" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Dried Filet of Catfish" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Dried Filet of Cave Angler" :  [{"n" : "Fish", "e" : 20, "c" : 30}],
 "Dried Filet of Cave Sculpin" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Dried Filet of Cavelacanth" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Dried Filet of Chub" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Dried Filet of Cod" :  [{"n" : "Fish", "e" : 15, "c" : 15}],
 "Dried Filet of Eel" :  [{"n" : "Fish", "e" : 40, "c" : 5}],
 "Dried Filet of Grayling" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Dried Filet of Haddock" :  [{"n" : "Fish", "e" : 30, "c" : 8}],
 "Dried Filet of Herring" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Dried Filet of Ide" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Dried Filet of Lavaret" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Dried Filet of Mackerel" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Dried Filet of Mullet" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Dried Filet of Pale Ghostfish" :  [{"n" : "Fish", "e" : 20, "c" : 17}],
 "Dried Filet of Perch" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Dried Filet of Pike" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Dried Filet of Plaice" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Dried Filet of Pomfret" :  [{"n" : "Fish", "e" : 18, "c" : 10}],
 "Dried Filet of Roach" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Dried Filet of Rose Fish" :  [{"n" : "Fish", "e" : 13, "c" : 13}],
 "Dried Filet of Ruffe" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Dried Filet of Saithe" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Dried Filet of Salmon" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Dried Filet of Silver Bream" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Dried Filet of Smelt" :  [{"n" : "Fish", "e" : 13, "c" : 13}],
 "Dried Filet of Sturgeon" :  [{"n" : "Fish", "e" : 5, "c" : 40}],
 "Dried Filet of Tench" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Dried Filet of Trout" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Dried Filet of Whiting" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Dried Filet of Zander" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Dried Filet of Zope" :  [{"n" : "Fish", "e" : 30, "c" : 10}],
 "Dried Morels" :  [{"n" : "Mushrooms", "e" : 13, "c" : 13}],
 "Egg Cake" :  [{"n" : "Fowl & Poultry", "e" : 25, "c" : 32}, {"n" : "Bread", "e" : 15, "c" : 20}],
 "Elderberries" :  [{"n" : "Berries", "e" : 20, "c" : 8}],
 "Elk Dog" :  [{"n" : "Sausage", "e" : 25, "c" : 32}, {"n" : "Game", "e" : 25, "c" : 16}],
 "Encumbered Roast" :  [{"n" : "Meat", "e" : 30, "c" : 30}, {"n" : "Vegetables", "e" : 15, "c" : 20}],
 "Escargots d'Amour" :  [{"n" : "Creepies & Crawlies", "e" : 40, "c" : 25}],
 "Fat-Braised Veg" :  [{"n" : "Offal", "e" : 20, "c" : 35}],
 "Feta" :  [{"n" : "Cheese", "e" : 20, "c" : 35}],
 "Field Blewits" :  [{"n" : "Mushrooms", "e" : 10, "c" : 20}],
 "Fish in Tears" :  [{"n" : "Fish", "e" : 40, "c" : 20}],
 "Fishballs" :  [{"n" : "Fish", "e" : 20, "c" : 40}],
 "Fishpie" :  [{"n" : "Fish", "e" : 25, "c" : 32}, {"n" : "Bread", "e" : 30, "c" : 20}],
 "Fishsticks" :  [{"n" : "Fish", "e" : 30, "c" : 10}, {"n" : "Bread", "e" : 30, "c" : 10}],
 "Fishwrap" :  [{"n" : "Fish", "e" : 20, "c" : 30}],
 "Fishy Eyeball" :  [{"n" : "Fish", "e" : 20, "c" : 10}, {"n" : "Offal", "e" : 25, "c" : 4}],
 "Formaela" :  [{"n" : "Cheese", "e" : 30, "c" : 35}],
 "Fox Fuet" :  [{"n" : "Sausage", "e" : 40, "c" : 20}],
 "Fox Wurst" :  [{"n" : "Sausage", "e" : 32, "c" : 25}],
 "Fruit Pie" :  [{"n" : "Fruit", "e" : 30, "c" : 25}, {"n" : "Sweets & Desserts", "e" : 25, "c" : 22}],
 "Fruit Sorbet" :  [{"n" : "Sweets & Desserts", "e" : 35, "c" : 20}],
 "Fruitroast" :  [{"n" : "Fruit", "e" : 30, "c" : 20}],
 "Fried Egg" :  [{"n" : "Fowl & Poultry", "e" : 40, "c" : 8}],
 "Garrotxa" :  [{"n" : "Cheese", "e" : 23, "c" : 40}],
 "Gbejna" :  [{"n" : "Cheese", "e" : 40, "c" : 15}],
 "Generic Gouda" :  [{"n" : "Cheese", "e" : 30, "c" : 25}],
 "Gevrik" :  [{"n" : "Cheese", "e" : 35, "c" : 30}],
 "Giant Puffball" :  [{"n" : "Mushrooms", "e" : 20, "c" : 10}],
 "Glazed Grazer Dog" :  [{"n" : "Sausage", "e" : 30, "c" : 25}],
 "Glazed Honeyons" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}],
 "Goat's Curd" :  [{"n" : "Dairy", "e" : 30, "c" : 20}],
 "Gooseberry" :  [{"n" : "Berries", "e" : 10, "c" : 15}],
 "Grapes" :  [{"n" : "Fruit", "e" : 30, "c" : 12}],
 "Graviera" :  [{"n" : "Cheese", "e" : 35, "c" : 20}],
 "Green Kelp" :  [{"n" : "Vegetables", "e" : 10, "c" : 40}, {"n" : "Fish", "e" : 5, "c" : 40}],
 "Greenleaf Pie" :  [{"n" : "Bread", "e" : 35, "c" : 20}, {"n" : "Vegetables", "e" : 30, "c" : 20}],
 "Grilled Frog Legs" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 30}],
 "Grub" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 20}],
 "Grub Pie" :  [{"n" : "Forage", "e" : 32, "c" : 25}, {"n" : "Bread", "e" : 25, "c" : 20}],
 "Haggis" :  [{"n" : "Offal", "e" : 35, "c" : 20}],
 "Halloumi" :  [{"n" : "Cheese", "e" : 40, "c" : 20}],
 "Harmesan Cheese" :  [{"n" : "Cheese", "e" : 35, "c" : 30}],
 "Hazelnut" :  [{"n" : "Nuts & Seeds", "e" : 10, "c" : 15}],
 "Head of Lettuce" :  [{"n" : "Vegetables", "e" : 20, "c" : 20}],
 "Honey Gruel" :  [{"n" : "Nuts & Seeds", "e" : 20, "c" : 20}],
 "Honey'd Bear" :  [{"n" : "Meat", "e" : 20, "c" : 35}],
 "Honeybun" :  [{"n" : "Sweets & Desserts", "e" : 25, "c" : 30}],
 "Hop Jellies" :  [{"n" : "Sweets & Desserts", "e" : 20, "c" : 40}],
 "Hot Wings" :  [{"n" : "Meat", "e" : 30, "c" : 20}],
 "Indigo Cap" :  [{"n" : "Mushrooms", "e" : 10, "c" : 20}],
 "Jelly Cake" :  [{"n" : "Sweets & Desserts", "e" : 25, "c" : 30}],
 "Jorbonzola" :  [{"n" : "Cheese", "e" : 35, "c" : 32}],
 "Jotun's Morsel" :  [{"n" : "Meat", "e" : 40, "c" : 20}],
 "Kasseri" :  [{"n" : "Cheese", "e" : 30, "c" : 20}],
 "Kebab Meat" :  [{"n" : "Meat", "e" : 20, "c" : 5}],
 "King of the Woods" :  [{"n" : "Sausage", "e" : 25, "c" : 36}],
 "Kvann" :  [{"n" : "Vegetables", "e" : 20, "c" : 10}],
 "Lamb & Lynx" :  [{"n" : "Sausage", "e" : 30, "c" : 25}],
 "Lamb Sausages" :  [{"n" : "Sausage", "e" : 27, "c" : 35}],
 "Laurel Crowned Roast" :  [{"n" : "Meat", "e" : 40, "c" : 17}],
 "Leeky Fowl" :  [{"n" : "Vegetables", "e" : 20, "c" : 40}, {"n" : "Fowl & Poultry", "e" : 20, "c" : 20}],
 "Lettuce Leaf" :  [{"n" : "Vegetables", "e" : 10, "c" : 40}],
 "Lingon Loaf" :  [{"n" : "Berries", "e" : 35, "c" : 20}, {"n" : "Bread", "e" : 25, "c" : 16}],
 "Lingonberries" :  [{"n" : "Forage", "e" : 10, "c" : 20}],
 "Linseed Loaf" :  [{"n" : "Bread", "e" : 40, "c" : 20}],
 "Liver & Onions" :  [{"n" : "Offal", "e" : 30, "c" : 35}],
 "Lizard on Scales" :  [{"n" : "Creepies & Crawlies", "e" : 35, "c" : 20}, {"n" : "Nuts & Seeds", "e" : 20, "c" : 10}],
 "Lynxalami" :  [{"n" : "Sausage", "e" : 32, "c" : 25}],
 "Magpie" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 25}],
 "Majorero" :  [{"n" : "Cheese", "e" : 25, "c" : 40}],
 "Manchego" :  [{"n" : "Cheese", "e" : 35, "c" : 28}],
 "Marrow Cake" :  [{"n" : "Offal", "e" : 25, "c" : 30}, {"n" : "Bread", "e" : 20, "c" : 10}],
 "Marrow Roast" :  [{"n" : "Offal", "e" : 40, "c" : 20}, {"n" : "Meat", "e" : 20, "c" : 20}],
 "Marsh-Mallow" :  [{"n" : "Forage", "e" : 10, "c" : 25}],
 "Meat-in-Jelly" :  [{"n" : "Creepies & Crawlies", "e" : 20, "c" : 35}, {"n" : "Meat", "e" : 20, "c" : 15}],
 "Meatpie" :  [{"n" : "Meat", "e" : 30, "c" : 30}, {"n" : "Bread", "e" : 30, "c" : 15}],
 "Medlar" :  [{"n" : "Fruit", "e" : 12, "c" : 12}],
 "Midnight Blue Cheese" :  [{"n" : "Cheese", "e" : 40, "c" : 30}],
 "Molehill" :  [{"n" : "Meat", "e" : 20, "c" : 40}, {"n" : "Vegetables", "e" : 20, "c" : 20}],
 "Moodog" :  [{"n" : "Sausage", "e" : 25, "c" : 36}],
 "Mothzarella" :  [{"n" : "Cheese", "e" : 30, "c" : 30}],
 "Moules Frites" :  [{"n" : "Fish", "e" : 35, "c" : 25}],
 "Mulberry" :  [{"n" : "Berries", "e" : 20, "c" : 5}],
 "Mushroom & Onion Pirozhki" :  [{"n" : "Bread", "e" : 35, "c" : 20}, {"n" : "Mushrooms", "e" : 20, "c" : 25}],
 "Mushroom Mash" :  [{"n" : "Mushrooms", "e" : 35, "c" : 25}],
 "Mushroom Pie" :  [{"n" : "Mushrooms", "e" : 35, "c" : 24}, {"n" : "Bread", "e" : 15, "c" : 10}],
 "Mushroom-Burst Glutton" :  [{"n" : "Meat", "e" : 20, "c" : 35}, {"n" : "Mushrooms", "e" : 20, "c" : 10}],
 "Mushrooms in Jelly" :  [{"n" : "Creepies & Crawlies", "e" : 20, "c" : 40}, {"n" : "Mushrooms", "e" : 15, "c" : 20}],
 "Musky Milben" :  [{"n" : "Cheese", "e" : 32, "c" : 30}],
 "Nutjerky" :  [{"n" : "Nuts & Seeds", "e" : 30, "c" : 20}],
 "Olive" :  [{"n" : "Vegetables", "e" : 15, "c" : 10}],
 "Olive Bread" :  [{"n" : "Vegetables", "e" : 40, "c" : 20}, {"n" : "Fruit", "e" : 25, "c" : 20}],
 "Omelette" :  [{"n" : "Fowl & Poultry", "e" : 32, "c" : 25}],
 "Onion Rings" :  [{"n" : "Vegetables", "e" : 30, "c" : 25}, {"n" : "Bread", "e" : 10, "c" : 20}],
 "Onion Salad" :  [{"n" : "Vegetables", "e" : 32, "c" : 25}, {"n" : "Bread", "e" : 0, "c" : 0}],
 "Onion Skewer" :  [{"n" : "Meat", "e" : 20, "c" : 40}, {"n" : "Vegetables", "e" : 20, "c" : 20}],
 "Onioned Escargot" :  [{"n" : "Creepies & Crawlies", "e" : 40, "c" : 22}],
 "Opened Oyster" :  [{"n" : "Fish", "e" : 20, "c" : 10}, {"n" : "Forage", "e" : 20, "c" : 5}],
 "Oscypki" :  [{"n" : "Cheese", "e" : 30, "c" : 40}],
 "Pancake" :  [{"n" : "Dairy", "e" : 35, "c" : 20}, {"n" : "Fowl & Poultry", "e" : 35, "c" : 20}],
 "Parasol Mushroom" :  [{"n" : "Mushrooms", "e" : 5, "c" : 30}],
 "Parboiled Morels" :  [{"n" : "Forage", "e" : 8, "c" : 8}, {"n" : "Mushrooms", "e" : 10, "c" : 10}],
 "Pea Pie" :  [{"n" : "Vegetables", "e" : 32, "c" : 25}, {"n" : "Bread", "e" : 16, "c" : 25}],
 "Peapod" :  [{"n" : "Vegetables", "e" : 10, "c" : 35}],
 "Pear" :  [{"n" : "Fruit", "e" : 20, "c" : 10}],
 "Pecorino" :  [{"n" : "Cheese", "e" : 30, "c" : 20}],
 "Perched Perch" :  [{"n" : "Fish", "e" : 25, "c" : 25}],
 "Persimmon" :  [{"n" : "Fruit", "e" : 15, "c" : 10}],
 "Picodon" :  [{"n" : "Cheese", "e" : 30, "c" : 25}],
 "Piglet Wursts" :  [{"n" : "Sausage", "e" : 30, "c" : 31}],
 "Plum" :  [{"n" : "Fruit", "e" : 13, "c" : 20}],
 "Poached Wolverine" :  [{"n" : "Meat", "e" : 32, "c" : 25}, {"n" : "Fowl & Poultry", "e" : 20, "c" : 15}],
 "Pommace Perdue" :  [{"n" : "Fruit", "e" : 36, "c" : 25}, {"n" : "Dairy", "e" : 16, "c" : 25}],
 "Poppy Pod" :  [{"n" : "Vegetables", "e" : 15, "c" : 20}],
 "Poultry Pot Pie" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 35}, {"n" : "Bread", "e" : 20, "c" : 15}],
 "Pumpkin Bread" :  [{"n" : "Bread", "e" : 40, "c" : 20}],
 "Pumpkin Flesh" :  [{"n" : "Vegetables", "e" : 20, "c" : 20}],
 "Pumpkin Pie" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}],
 "Pumpkin Stew" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}],
 "Quince" :  [{"n" : "Fruit", "e" : 20, "c" : 13}],
 "Rabbit Food" :  [{"n" : "Forage", "e" : 30, "c" : 20}],
 "Raisin Butter-Cake" :  [{"n" : "Sweets & Desserts", "e" : 40, "c" : 20}, {"n" : "Dairy", "e" : 30, "c" : 10}],
 "Raisins" :  [{"n" : "Fruit", "e" : 40, "c" : 10}],
 "Raspberry" :  [{"n" : "Berries", "e" : 10, "c" : 10}],
 "Rat-on-a-Stick" :  [{"n" : "Creepies & Crawlies", "e" : 30, "c" : 20}, {"n" : "Meat", "e" : 10, "c" : 20}],
 "Raw Beef" :  [{"n" : "Meat", "e" : 30, "c" : 10}],
 "Red Apple" :  [{"n" : "Fruit", "e" : 20, "c" : 10}],
 "Red-Shred Salad" :  [{"n" : "Vegetables", "e" : 30, "c" : 35}],
 "Redcurrant" :  [{"n" : "Berries", "e" : 10, "c" : 10}],
 "Ring of Brodgar (Baking)" :  [{"n" : "Bread", "e" : 35, "c" : 22}],
 "Ring of Brodgar (Seafood)" :  [{"n" : "Fish", "e" : 25, "c" : 30}],
 "Roast Adder" :  [{"n" : "Creepies & Crawlies", "e" : 40, "c" : 15}],
 "Roast Ant" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 30}],
 "Roast Badger" :  [{"n" : "Meat", "e" : 40, "c" : 13}],
 "Roast Bat" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Roast Bear" :  [{"n" : "Meat", "e" : 40, "c" : 5}, {"n" : "Game", "e" : 40, "c" : 5}],
 "Roast Beaver" :  [{"n" : "Meat", "e" : 10, "c" : 50}],
 "Roast Beef" :  [{"n" : "Meat", "e" : 30, "c" : 10}],
 "Roast Bog Turtle" :  [{"n" : "Meat", "e" : 15, "c" : 20}],
 "Roast Boreworm" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Roast Cachalot" :  [{"n" : "Meat", "e" : 20, "c" : 20}, {"n" : "Fish", "e" : 20, "c" : 20}],
 "Roast Cave Louse" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 40}],
 "Roast Caverat" :  [{"n" : "Meat", "e" : 20, "c" : 25}],
 "Roast Chasm Conch" :  [{"n" : "Meat", "e" : 50, "c" : 10}],
 "Roast Chestnut" :  [{"n" : "Nuts & Seeds", "e" : 10, "c" : 15}],
 "Roast Chevon" :  [{"n" : "Meat", "e" : 25, "c" : 20}],
 "Roast Chicken" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 10}],
 "Crab" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Roast Eagle Owl" :  [{"n" : "Fowl & Poultry", "e" : 60, "c" : 10}],
 "Roast Filet of Abyss Gazer" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Roast Filet of Asp" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Roast Filet of Bass" :  [{"n" : "Fish", "e" : 15, "c" : 13}],
 "Roast Filet of Bream" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Roast Filet of Brill" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Roast Filet of Burbot" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Roast Filet of Carp" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Roast Filet of Catfish" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Roast Filet of Cave Angler" :  [{"n" : "Fish", "e" : 20, "c" : 30}],
 "Roast Filet of Cave Sculpin" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Roast Filet of Cavelacanth" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Roast Filet of Chub" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Roast Filet of Cod" :  [{"n" : "Fish", "e" : 15, "c" : 15}],
 "Roast Filet of Eel" :  [{"n" : "Fish", "e" : 40, "c" : 5}],
 "Roast Filet of Grayling" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Roast Filet of Haddock" :  [{"n" : "Fish", "e" : 30, "c" : 8}],
 "Roast Filet of Herring" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Roast Filet of Ide" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Roast Filet of Lavaret" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Roast Filet of Mackerel" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Roast Filet of Mullet" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Roast Filet of Pale Ghostfish" :  [{"n" : "Fish", "e" : 20, "c" : 17}],
 "Roast Filet of Perch" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Roast Filet of Pike" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Roast Filet of Plaice" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Roast Filet of Pomfret" :  [{"n" : "Fish", "e" : 18, "c" : 10}],
 "Roast Filet of Roach" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Roast Filet of Rose Fish" :  [{"n" : "Fish", "e" : 13, "c" : 13}],
 "Roast Filet of Ruffe" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Roast Filet of Saithe" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Roast Filet of Salmon" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Roast Filet of Silver Bream" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Roast Filet of Smelt" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Roast Filet of Sturgeon" :  [{"n" : "Fish", "e" : 5, "c" : 40}],
 "Roast Filet of Tench" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Roast Filet of Trout" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Roast Filet of Whiting" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Roast Filet of Zander" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Roast Filet of Zope" :  [{"n" : "Fish", "e" : 30, "c" : 10}],
 "Roast Fox" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Roast Golden Eagle" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 20}],
 "Roast Grey Seal" :  [{"n" : "Meat", "e" : 30, "c" : 10}, {"n" : "Fish", "e" : 10, "c" : 20}],
 "Roast Hedgehog" :  [{"n" : "Forage", "e" : 30, "c" : 10}],
 "Roast Horse" :  [{"n" : "Meat", "e" : 30, "c" : 25}],
 "Roast Lynx" :  [{"n" : "Game", "e" : 40, "c" : 15}],
 "Roast Magpie" :  [{"n" : "Forage", "e" : 35, "c" : 20}],
 "Roast Mallard" :  [{"n" : "Fowl & Poultry", "e" : 40, "c" : 10}],
 "Roast Mammoth" :  [{"n" : "Game", "e" : 40, "c" : 20}],
 "Roast Meat" :  [],
 "Roast Mole" :  [{"n" : "Meat", "e" : 20, "c" : 35}],
 "Roast Moose" :  [{"n" : "Game", "e" : 30, "c" : 20}],
 "Roast Mutton" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Roast Otter" :  [{"n" : "Meat", "e" : 20, "c" : 25}],
 "Roast Pork" :  [{"n" : "Meat", "e" : 20, "c" : 20}],
 "Roast Ptarmigan" :  [{"n" : "Fowl & Poultry", "e" : 15, "c" : 20}],
 "Roast Quail" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 20}],
 "Roast Rabbit" :  [{"n" : "Meat", "e" : 10, "c" : 40}],
 "Roast Reindeer Venison" :  [{"n" : "Meat", "e" : 20, "c" : 30}],
 "Roast Roach Wrap" :  [{"n" : "Fish", "e" : 10, "c" : 40}, {"n" : "Bread", "e" : 30, "c" : 10}],
 "Roast Seagull" :  [{"n" : "Forage", "e" : 15, "c" : 20}],
 "Roast Squirrel" :  [{"n" : "Forage", "e" : 20, "c" : 30}],
 "Roast Swan" :  [{"n" : "Fowl & Poultry", "e" : 25, "c" : 25}],
 "Roast Troll" :  [{"n" : "Meat", "e" : 35, "c" : 20}],
 "Roast Venison" :  [{"n" : "Game", "e" : 15, "c" : 25}],
 "Roast Walrus" :  [{"n" : "Meat", "e" : 25, "c" : 20}, {"n" : "Fish", "e" : 10, "c" : 20}],
 "Roast Wild Beef" :  [{"n" : "Meat", "e" : 20, "c" : 20}],
 "Roast Wild Mutton" :  [{"n" : "Game", "e" : 10, "c" : 50}],
 "Roast Wild Pork" :  [{"n" : "Game", "e" : 20, "c" : 20}],
 "Roast Wildgoat" :  [{"n" : "Game", "e" : 30, "c" : 20}],
 "Roast Wildhorse" :  [{"n" : "Meat", "e" : 10, "c" : 60}],
 "Roast Wolf" :  [{"n" : "Meat", "e" : 10, "c" : 40}, {"n" : "Game", "e" : 10, "c" : 40}],
 "Roast Wolverine" :  [{"n" : "Meat", "e" : 20, "c" : 35}],
 "Roast Wood Grouse" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 25}],
 "Roasthopper" :  [{"n" : "Creepies & Crawlies", "e" : 10, "c" : 50}],
 "Robiola" :  [{"n" : "Cheese", "e" : 25, "c" : 30}],
 "Roncal" :  [{"n" : "Cheese", "e" : 30, "c" : 20}],
 "Running Rabbit Sausage" :  [{"n" : "Forage", "e" : 30, "c" : 25}],
 "Sacrebleu" :  [{"n" : "Dairy", "e" : 40, "c" : 20}, {"n" : "Berries", "e" : 40, "c" : 20}],
 "Seaberries" :  [{"n" : "Berries", "e" : 10, "c" : 10}],
 "Seal Burger" :  [{"n" : "Meat", "e" : 25, "c" : 32}, {"n" : "Fish", "e" : 25, "c" : 20}],
 "Seedcrisp Flatbread" :  [{"n" : "Nuts & Seeds", "e" : 32, "c" : 25}],
 "Sheep's Curd" :  [{"n" : "Dairy", "e" : 30, "c" : 20}],
 "Shepherd's Pie" :  [{"n" : "Bread", "e" : 36, "c" : 25}, {"n" : "Meat", "e" : 25, "c" : 16}],
 "Sloan Berries" :  [{"n" : "Berries", "e" : 20, "c" : 5}],
 "Sorb Apple" :  [{"n" : "Fruit", "e" : 10, "c" : 25}],
 "Spicy Salad" :  [{"n" : "Vegetables", "e" : 35, "c" : 25}],
 "Spindly Taproot" :  [],
 "Spitroast Abyss Gazer" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Spitroast Adder" :  [{"n" : "Creepies & Crawlies", "e" : 40, "c" : 15}],
 "Spitroast Asp" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Spitroast Badger" :  [{"n" : "Meat", "e" : 40, "c" : 13}],
 "Spitroast Bass" :  [{"n" : "Fish", "e" : 15, "c" : 13}],
 "Spitroast Bat" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Spitroast Bear" :  [{"n" : "Meat", "e" : 40, "c" : 5}, {"n" : "Game", "e" : 40, "c" : 5}],
 "Spitroast Beaver" :  [{"n" : "Meat", "e" : 10, "c" : 50}],
 "Spitroast Beef" :  [{"n" : "Meat", "e" : 30, "c" : 10}],
 "Spitroast Bog Turtle" :  [{"n" : "Meat", "e" : 15, "c" : 20}],
 "Spitroast Boreworm" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Spitroast Bream" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Spitroast Brill" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Spitroast Burbot" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Spitroast Carp" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Spitroast Catfish" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Spitroast Cave Angler" :  [{"n" : "Fish", "e" : 20, "c" : 30}],
 "Spitroast Cave Louse" :  [{"n" : "Creepies & Crawlies", "e" : 15, "c" : 40}],
 "Spitroast Cave Sculpin" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Spitroast Cavelacanth" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Spitroast Caverat" :  [{"n" : "Meat", "e" : 20, "c" : 25}],
 "Spitroast Chevon" :  [{"n" : "Meat", "e" : 25, "c" : 20}],
 "Spitroast Chicken" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 10}],
 "Spitroast Chub" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Spitroast Cod" :  [{"n" : "Fish", "e" : 15, "c" : 15}],
 "Spitroast Eagle Owl" :  [{"n" : "Fowl & Poultry", "e" : 60, "c" : 10}],
 "Spitroast Eel" :  [{"n" : "Fish", "e" : 40, "c" : 5}],
 "Spitroast Fox" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Spitroast Golden Eagle" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 20}],
 "Spitroast Grayling" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Spitroast Grey Seal" :  [{"n" : "Meat", "e" : 30, "c" : 10}, {"n" : "Fish", "e" : 10, "c" : 20}],
 "Spitroast Haddock" :  [{"n" : "Fish", "e" : 30, "c" : 8}],
 "Spitroast Hedgehog" :  [{"n" : "Forage", "e" : 30, "c" : 10}],
 "Spitroast Herring" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Spitroast Horse" :  [{"n" : "Meat", "e" : 30, "c" : 25}],
 "Spitroast Ide" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Spitroast Lavaret" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Spitroast Lynx" :  [{"n" : "Game", "e" : 40, "c" : 15}],
 "Spitroast Mackerel" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Spitroast Magpie" :  [{"n" : "Forage", "e" : 35, "c" : 20}],
 "Spitroast Mallard" :  [{"n" : "Fowl & Poultry", "e" : 40, "c" : 10}],
 "Spitroast Mole" :  [{"n" : "Meat", "e" : 20, "c" : 35}],
 "Spitroast Moose" :  [{"n" : "Game", "e" : 30, "c" : 20}],
 "Spitroast Mullet" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Spitroast Mutton" :  [{"n" : "Meat", "e" : 15, "c" : 40}],
 "Spitroast Otter" :  [{"n" : "Meat", "e" : 20, "c" : 25}],
 "Spitroast Pale Ghostfish" :  [{"n" : "Fish", "e" : 20, "c" : 17}],
 "Spitroast Perch" :  [{"n" : "Fish", "e" : 20, "c" : 10}],
 "Spitroast Pike" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Spitroast Plaice" :  [{"n" : "Fish", "e" : 13, "c" : 20}],
 "Spitroast Pomfret" :  [{"n" : "Fish", "e" : 18, "c" : 10}],
 "Spitroast Ptarmigan" :  [{"n" : "Fowl & Poultry", "e" : 15, "c" : 20}],
 "Spitroast Quail" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 20}],
 "Spitroast Rabbit" :  [{"n" : "Meat", "e" : 10, "c" : 40}],
 "Spitroast Reindeer Venison" :  [{"n" : "Meat", "e" : 20, "c" : 30}],
 "Spitroast Roach" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Spitroast Rose Fish" :  [{"n" : "Fish", "e" : 13, "c" : 13}],
 "Spitroast Ruffe" :  [{"n" : "Fish", "e" : 15, "c" : 20}],
 "Spitroast Saithe" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Spitroast Salmon" :  [{"n" : "Fish", "e" : 20, "c" : 13}],
 "Spitroast Seagull" :  [{"n" : "Forage", "e" : 15, "c" : 20}],
 "Spitroast Silver Bream" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Spitroast Smelt" :  [{"n" : "Fish", "e" : 20, "c" : 20}],
 "Spitroast Squirrel" :  [{"n" : "Forage", "e" : 20, "c" : 30}],
 "Spitroast Sturgeon" :  [{"n" : "Fish", "e" : 5, "c" : 40}],
 "Spitroast Swan" :  [{"n" : "Fowl & Poultry", "e" : 25, "c" : 25}],
 "Spitroast Tench" :  [{"n" : "Fish", "e" : 50, "c" : 5}],
 "Spitroast Trout" :  [{"n" : "Fish", "e" : 10, "c" : 25}],
 "Spitroast Venison" :  [{"n" : "Game", "e" : 15, "c" : 25}],
 "Spitroast Walrus" :  [{"n" : "Meat", "e" : 25, "c" : 20}, {"n" : "Fish", "e" : 10, "c" : 20}],
 "Spitroast Whiting" :  [{"n" : "Fish", "e" : 20, "c" : 15}],
 "Spitroast Wild Beef" :  [{"n" : "Meat", "e" : 20, "c" : 20}],
 "Spitroast Wild Pork" :  [{"n" : "Game", "e" : 20, "c" : 20}],
 "Spitroast Wildgoat" :  [{"n" : "Game", "e" : 30, "c" : 20}],
 "Spitroast Wolf" :  [{"n" : "Meat", "e" : 10, "c" : 40}, {"n" : "Game", "e" : 10, "c" : 40}],
 "Spitroast Wolverine" :  [{"n" : "Meat", "e" : 20, "c" : 35}],
 "Spitroast Wood Grouse" :  [{"n" : "Fowl & Poultry", "e" : 20, "c" : 25}],
 "Spitroast Zander" :  [{"n" : "Fish", "e" : 10, "c" : 30}],
 "Spitroast Zope" :  [{"n" : "Fish", "e" : 30, "c" : 10}],
 "Spring Stew" :  [{"n" : "Vegetables", "e" : 20, "c" : 40}],
 "Stalagoom" :  [{"n" : "Mushrooms", "e" : 10, "c" : 50}],
 "Steak & Tubers" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}, {"n" : "Meat", "e" : 15, "c" : 15}],
 "Stinging Salad" :  [{"n" : "Vegetables", "e" : 32, "c" : 25}, {"n" : "Forage", "e" : 20, "c" : 20}],
 "Strawberries in Cream" :  [{"n" : "Sweets & Desserts", "e" : 30, "c" : 20}, {"n" : "Dairy", "e" : 20, "c" : 30}],
 "Strawberries" :  [{"n" : "Berries", "e" : 5, "c" : 20}],
 "Strawberry Cake" :  [{"n" : "Berries", "e" : 20, "c" : 35}],
 "Sunlit Stilton" :  [{"n" : "Cheese", "e" : 30, "c" : 35}],
 "Swan Neck" :  [{"n" : "Sausage", "e" : 30, "c" : 15}, {"n" : "Fowl & Poultry", "e" : 30, "c" : 15}],
 "Sweet Beets" :  [{"n" : "Vegetables", "e" : 30, "c" : 30}],
 "Tame Game Liverwurst" :  [{"n" : "Sausage", "e" : 30, "c" : 30}],
 "Tasty Emmentaler" :  [{"n" : "Cheese", "e" : 25, "c" : 35}],
 "Troll Ear" :  [],
 "Troll Mushrooms" :  [{"n" : "Mushrooms", "e" : 50, "c" : 15}],
 "Troll Nose" :  [],
 "Troll Tail" :  [],
 "Troll's Third Eye" :  [],
 "Tuber Mash" :  [{"n" : "Vegetables", "e" : 20, "c" : 40}],
 "Turnip" :  [{"n" : "Vegetables", "e" : 25, "c" : 20}],
 "Turnip Fries" :  [{"n" : "Vegetables", "e" : 30, "c" : 20}],
 "Two-Bird Skewer" :  [{"n" : "Fowl & Poultry", "e" : 30, "c" : 32}],
 "Walnut" :  [{"n" : "Nuts & Seeds", "e" : 13, "c" : 13}],
 "Walrus & Carpenter" :  [{"n" : "Sausage", "e" : 35, "c" : 20}, {"n" : "Fish", "e" : 20, "c" : 10}],
 "Weird Beetroot" :  [{"n" : "Vegetables", "e" : 20, "c" : 25}],
 "Wellplaiced Pie" :  [{"n" : "Fish", "e" : 30, "c" : 30}],
 "Withercorn" :  [{"n" : "Nuts & Seeds", "e" : 13, "c" : 12}],
 "Wonderful Wilderness Wurst" :  [{"n" : "Game", "e" : 25, "c" : 20}, {"n" : "Meat", "e" : 40, "c" : 10}],
 "Yellowfeet" :  [{"n" : "Forage", "e" : 25, "c" : 10}],
 "Zamorano" :  [{"n" : "Cheese", "e" : 40, "c" : 20}],
 "Zesty Brill" :  [{"n" : "Fish", "e" : 35, "c" : 20}]
}