var gl_nofx = ["Mix", "Spring Water", "Rendered Animal Fat", "No spice", "Domestic Honey"];
var gl_spice = [
	"No spice",
	"Black Pepper",
	"Chives",
	"Dill",
	"Kvann",
	"Laurel Leaves"
];
var gl_honey = [
	"Domestic Honey",
	"Domestic Honey",
	"Wild-bee Honey"
];
var gl_flour = [
	"Barley Flour",
	"Millet Flour",
	"Wheat Flour"
];
var gl_milk = [
	"Mix",
	"Cowsmilk",
	"Sheepsmilk",
	"Goatsmilk",
	"Aurochs Milk"	
];
var gl_butter = [
	"Mix",
	"Cowsmilk",
	"Sheepsmilk",
	"Goatsmilk",
	"Aurochs Milk"	
];
var gl_water = [
		"Mix",
		"Spring Water"
];
var gl_pork = [
	"Pork",
	"Boar"
];
var gl_beef = [
	"Beef",
	"Wild Beef"
];
var gl_mutton = [
	"Mutton",
	"Wild Mutton"
];
var gl_horse = [
	"Horse",
	"Wild Horse"
];
var gl_onion = [
	"Leek",
	"Red Onion",
	"Yellow Onion"
];
var gl_salad = [
	"Beetroot Leaves",
	"Driftkelp",
	"Green Kelp",
	"Heartwood Leaves",
	"Lettuce Leaf",
	"Marsh-Mallow",
	"Stinging Nettle"
];
var gl_sweetener = [
	"Birch Sap",
	"Domestic Honey",
	"Maple Sap",
	"Domestic Honey",
	"Wild-bee Honey"
];
var gl_mushroom = [
	"Bay Bolete",
	"Black Truffles",
	"Black Trumpets",
	"Bloated Bolete",
	"Cave Lantern",
	"Chantrelles",
	"Dried Morels",
	"Fairy Mushroom",
	"Field Blewits",
	"Giant Puffball",
	"Parasol Mushroom",
	"Parboiled Morels",
	"Troll Mushrooms",
	"White Truffles",
	"Yellowfeet"
];
var gl_poultry = [
	"Chicken",
	"Eagle Owl",
	"Golden Eagle",
	"Magpie",
	"Mallard",
	"Ptarmigan",
	"Seagull",
	"Quail",
	"Swan",
	"Wood Grouse"
];
var gl_fish = [
	"Abyss Gazer",
	"Asp",
	"Bream",
	"Brill",
	"Burbot",
	"Carp",
	"Catfish",
	"Cave angler",
	"Cave Sculpin",
	"Cavelacanth",
	"Chub",
	"Eel",
	"Grayling",
	"Ide",
	"Lavaret",
	"Pale Ghostfish",
	"Perch",
	"Pike",
	"Plaice",
	"Roach",
	"Ruffe",
	"Salmon",
	"Silver Bream",
	"Smelt",
	"Sturgeon",
	"Tench",
	"Trout",
	"Zander",
	"Zope",
	"Bass",
	"Cod",
	"Haddock",
	"Herring",
	"Mackerel",
	"Mullet",
	"Pomfret",
	"Rose fish",
	"Saithe",
	"Seahorse",
	"Whiting"
];
var gl_fat = [
	"Mix",
	"Cowsmilk",
	"Sheepsmilk",
	"Goatsmilk",
	"Aurochs Milk",
	"Rendered Animal Fat"
];
var gl_meat = [
	"Adder",
	"Ant",
	"Badger",
	"Bat",
	"Bear",
	"Beaver",
	"Beef",
	"Boar",
	"Boreworm",
	"Cave louse",
	"Chasm conch",
	"Chicken",
	"Eagle Owl",
	"Fox",
	"Goat",
	"Golden Eagle",
	"Grey Seal",
	"Hedgehog",
	"Horse",
	"Lynx",
	"Magpie",
	"Mallard",
	"Mammoth",
	"Mole",
	"Moose",
	"Mutton",
	"Otter",
	"Pork",
	"Ptarmigan",
	"Quail",
	"Rabbit",
	"Reindeer Venison",
	"Squirrel",
	"Seagull",
	"Swan",
	"Troll",
	"Venison",
	"Walrus",
	"Wild Beef",
	"Wild Horse",
	"Wild Mutton",
	"Wildgoat",
	"Wolf",
	"Wolverine",
	"Wood Grouse"
];
var gl_meatweird = [
	"Ant",
	"Boreworm",
	"Cave louse",
	"Chasm conch",
	"Troll"
];
var gl_carcass = [
	"Adder",
	"Bat",
	"Chicken",
	"Eagle Owl",
	"Golden Eagle",
	"Hedgehog",
	"Magpie",
	"Mallard",
	"Mole",
	"Ptarmigan",
	"Quail",
	"Rabbit",
	"Squirrel",
	"Swan",
	"Wood Grouse"
];
var gl_tuber = [
	"Beetroot",
	"Carrot",
	"Cavebulb",
	"Turnip"
];
var gl_fruit = [
	"Cherries",
	"Grapes",
	"Pear",
	"Plum",
	"Quince",
	"Red Apple"
];
var gl_berry = [
	"Blackberry",
	"Blackcurrant",
	"Blueberries",
	"Candleberry",
	"Dog Rose Hips",
	"Elderberries",
	"Gooseberry",
	"Grapes",
	"Lingonberries",
	"Mulberry",
	"Raspberry",
	"Redcurrant",
	"Seaberries",
	"Sloan Berries",
	"Strawberries"
];
var gl_fob = [
	"Blackberry",
	"Blackcurrant",
	"Blueberries",
	"Candleberry",
	"Cherries",
	"Dog Rose Hips",
	"Elderberries",
	"Gooseberry",
	"Grapes",
	"Lingonberries",
	"Mulberry",
	"Pear",
	"Plum",
	"Quince",
	"Raspberry",
	"Red Apple",
	"Redcurrant",
	"Seaberries",
	"Sloan Berries",
	"Strawberries"
];
var gl_vegetable = [
	"Beetroot Leaves",
	"Carrot",
	"Cavebulb",
	"Cucumber",
	"Green Kelp",
	"Lettuce Leaf",
	"Olive",
	"Peapod",
	"Pumpkin Flesh",
	"Turnip"
];
var go_inglists = {
	"beef" : gl_beef,
	"berry" : gl_berry,
	"butter" : gl_butter,
	"carcass" : gl_carcass,
	"fat" : gl_fat,
	"fish" : gl_fish,
	"flour" : gl_flour,
	"fob" : gl_fob,
	"fruit" : gl_fruit,
	"horse" : gl_horse,
	"honey" : gl_honey,
	"meat" : gl_meat,
	"meatweird" : gl_meatweird,
	"milk" : gl_milk,
	"mushroom" : gl_mushroom,
	"mutton" : gl_mutton,
	"onion" : gl_onion,
	"pork" : gl_pork,
	"poultry" : gl_poultry,
	"salad" : gl_salad,
	"spice" : gl_spice,
	"sweetener" : gl_sweetener,
	"tuber" : gl_tuber,
	"vegetable" : gl_vegetable,
	"water" : gl_water
};
var gl_food = [
	["Apple Pie", ["water", "flour", "butter"], {"con1" : 10}, 500, 3.5],
	["Autumn Steak", ["mushroom", "meat", "salad", "spice"], {"con1" : 4, "prc1" : 3, "prc2" : 2}, 800, 3],
	["Bark Bread", ["water", "flour"], {"con1" : 5, "wil1" : 5}, 500, 5],
	["Beaver Dog", ["mushroom"], {"con2" : 4, "csm1" : 2, "wil1" : 2}, 600, 2.5],
	["Blueberry Pie", ["water", "flour"], {"int1" : 4, "prc1" : 3}, 200, 3.5],
	["Bread", ["water", "flour"], {"con1" : 5}, 500, 5],
	["Carrot Cake", ["water", "flour", "butter"], {"prc1" : 7}, 500, 3],
	["Fish in Tears", ["fish", "fat", "onion"], {"agi1" : 4, "csm2" : 4}, 500, 2.5],
	["Fishwrap", ["berry", "fish", "spice"], {"int1" : 2, "prc1" : 3, "wil1" : 2}, 500, 2],
	["Greenleaf Pie", ["flour", "salad", "water"], {"int1" : 2, "con1" : 3, "wil1" : 1}, 500, 3],
	["Grubpie", ["water", "flour"], {"str2" : 3, "prc2" : 4, "wil2" : 4}, 600, 3],
	["Kebab Meat", ["meat", "spice"],	{"con1" : 2.0}, 200.0, 1.0],
	["Lingon Loaf", ["water", "flour"], {"con1" : 2, "csm1" : 2, "csm2" : 3}, 500, 3],
	["Linseed Loaf", ["water", "flour"], {"int1" : 1, "con1" : 2, "prc1" : 4}, 500, 3],
	["Magpie", ["water", "flour", "spice"], {"int2" : 3, "con1" : 3, "wil1" : 4}, 750, 4],
	["Mushroom-Burst Glutton", ["carcass", "mushroom", "spice"], {"con1" : 3, "prc1" : 3, "csm2" : 2}, 750, 2],
	["Spicy Salad", ["tuber", "salad", "onion", "spice"], {"str2" : 1, "agi1" : 2, "csm1" : 3}, 500, 2.5],
	["Meatpie", ["water", "flour", "meat", "spice"], {"str1" : 5, "con1" : 4}, 700, 5],
	["Mushroom & Onion Pirozhki", ["water", "flour", "onion", "mushroom"], {"con1" : 4, "dex1" : 4}, 350, 5],
	["Olive Bread",	[ "flour", "water" ],	{"str1" : 3.0, "agi2" : 2.0, "dex1" : 4.0}, 500.0, 2.0],
	["Pumpkin Bread", ["water", "flour"], {"con1" : 4, "csm1" : 2}, 500, 5],
	["Pumpkin Pie", ["water", "flour"], {"str1" : 2, "con1" : 6}, 300, 4],
	["Seedcrisp Flatbread", ["water", "flour"], {"str1" : 1, "con1" : 1, "wil2" : 2}, 500, 2],
	["Zesty Brill", ["onion"], {"str1" : 4, "dex1" : 4, "wil1" : 5}, 800, 2.5]
];
var gl_fepmod = [
	["Apple Pie", ["Barley Flour", "Aurochs Milk"], {"con1" : 5.85, "str1" : 5.4}], 
	["Apple Pie", ["Barley Flour", "Goatsmilk"], {"con1" : 6.75, "str1" : 2.625, "wil1" : 4.375}], 
	["Apple Pie", ["Barley Flour"], {"con1" : 8.998, "str1" : 3.501}], 
	["Apple Pie", ["Cowsmilk", "Barley Flour"], {"con1" : 6.75, "str1" : 7}], 
	["Apple Pie", ["Cowsmilk", "Millet Flour"], {"con1" : 9.68, "wil1" : 4.235}], 
	["Apple Pie", ["Cowsmilk", "Wheat Flour"], {"con1" : 9.7, "agi1" : 7.25}], 
	["Apple Pie", ["Goatsmilk", "Millet Flour"], {"con1" : 5.625, "dex1" : 4.9, "wil1" : 2.1437}], 
	["Apple Pie", ["Goatsmilk", "Wheat Flour"], {"con1" : 5.625, "dex1" : 4.9, "prc1" : 3.675}], 
	["Apple Pie", ["Millet Flour"], {"con1" : 8.0, "wil1" : 3.5}], 
	["Apple Pie", ["Sheepsmilk", "Barley Flour"], {"con1" : 6.748, "str1" : 2.622, "dex1" : 4.375}], 
	["Apple Pie", ["Sheepsmilk", "Millet Flour"], {"con1" : 7.7687, "csm1" : 4.9}],
	["Apple Pie", ["Sheepsmilk", "Wheat Flour"], {"con1" : 9.3, "csm1" : 4.9}], 
	["Apple Pie", ["Wheat Flour", "Aurochs Milk"], {"con1" : 8.55, "agi1" : 3.9}], 
	["Apple Pie", ["Wheat Flour"], {"con1" : 8.003, "agi1" : 6.004}], 
	["Autumn Steak", ["Driftkelp", "Swan", "Fairy Mushroom"], {"prc2" : 19.8, "prc1" : 27.0, "con1" : 36.0}], 
	["Bark Bread", ["Millet Flour"], {"con1" : 5.75, "wil1" : 5.0}], 
	["Beaver Dog", ["Bay Bolete"], {"con2" : 2.0, "wil1" : 2.0, "csm1" : 2.0, "dex2" : 3.0}], 
	["Beaver Dog", ["Chantrelles"], {"con2" : 4.0, "wil1" : 2.0, "csm1" : 1.2, "agi1" : 1.0}], 
	["Beaver Dog", ["Giant Puffball"], {"con2" : 1.6, "wil1" : 2.0, "csm1" : 2.0, "prc1" : 2.6}], 
	["Beaver Dog", ["Parasol Mushroom"], {"con2" : 3.0, "wil1" : 2.0, "csm1" : 2.0, "dex1" : 2.0}], 
	["Beaver Dog", ["Yellowfeet"], {"con2" : 4.0, "wil1" : 2.0, "csm1" : 1.4, "str1" : 1.0}], 
	["Blueberry Pie", ["Millet Flour"], {"int1" : 3.2, "prc1" : 3.0, "con1" : 1.4}], 
	["Bread", ["Millet Flour"], {"con1" : 4.0, "wil1" : 1.75}], 
	["Carrot Cake", ["Barley Flour"], {"prc1" : 6.3, "str1" : 2.45}], 
	["Carrot Cake", ["Cowsmilk", "Millet Flour"], {"prc1" : 3.9375, "str1" : 3.43, "wil1" : 1.5006}], 
	["Carrot Cake", ["Goatsmilk", "Millet Flour"], {"prc1" : 3.9375, "wil1" : 3.43, "con1" : 1.5006}], 
	["Carrot Cake", ["Millet Flour"], {"prc1" : 5.6, "con1" : 2.45}], 
	["Carrot Cake", ["Sheepsmilk", "Millet Flour"], {"prc1" : 3.9375, "dex1" : 3.43, "con1" : 1.5006}], 
	["Fish in Tears", ["Asp", "Goatsmilk", "Red Onion"], {"csm2" : 3.0, "agi1" : 2.8, "dex1" : 3.232, "int1" : 2.02}], 
	["Fish in Tears", ["Carp", "Yellow Onion", "Goatsmilk"], {"csm2" : 3.2, "agi1" : 0.75, "prc1" : 3.75, "str1" : 1.8, "dex1" : 2.1}], 
	["Fish in Tears", ["Goatsmilk", "Red Onion", "Chub"], {"csm2" : 3.0, "agi1" : 3.0, "dex1" : 2.24, "int1" : 1.12, "csm1" : 0.42}], 
	["Fish in Tears", ["Goatsmilk", "Red Onion", "Grayling"], {"csm2" : 3.0, "agi1" : 3.0, "dex1" : 2.24, "int1" : 0.98, "prc1" : 0.7}], 
	["Fish in Tears", ["Goatsmilk", "Red Onion", "Haddock"], {"csm2" : 3.0, "agi1" : 3.0, "dex1" : 2.24, "int1" : 1.834}], 
	["Fish in Tears", ["Goatsmilk", "Red Onion", "Rose fish"], {"csm2" : 3.0, "agi1" : 3.0, "dex1" : 2.24, "int1" : 0.98, "wil1" : 0.98}], 
	["Fish in Tears", ["Lavaret", "Goatsmilk", "Red Onion"], {"csm2" : 3.0, "agi1" : 1.65, "con1" : 3.2, "dex1" : 1.736, "int1" : 1.085}], 
	["Fish in Tears", ["Pike", "Goatsmilk", "Red Onion"], {"csm2" : 3.0, "agi1" : 1.8, "int1" : 4.72, "dex1" : 1.792}], 
	["Fish in Tears", ["Red Onion", "Aurochs Milk", "Burbot"], {"csm2" : 1.82, "agi1" : 3.2, "str1" : 2.8, "csm1" : 1.3}], 
	["Fish in Tears", ["Red Onion", "Aurochs Milk", "Trout"], {"csm2" : 2.6, "agi1" : 3.2, "str1" : 4.2}], 
	["Fish in Tears", ["Roach", "Yellow Onion", "Goatsmilk"], {"csm2" : 2.4, "agi1" : 3.2, "int1" : 1.2, "str1" : 1.8, "dex1" : 1.68}], 
	["Fish in Tears", ["Smelt", "Goatsmilk", "Red Onion"], {"csm2" : 3.0, "agi1" : 2.8, "csm1" : 1.2, "wil1" : 1.568, "int1" : 0.98}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Bream"], {"csm2" : 0.8, "agi1" : 3.0, "str1" : 1.35, "wil1" : 2.03, "csm1" : 3.2}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Burbot"], {"csm2" : 3.2, "agi1" : 3.0, "str1" : 0.945, "wil1" : 2.03, "csm1" : 0.675}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Mullet"], {"csm2" : 3.2, "agi1" : 4.015, "str1" : 1.35, "wil1" : 1.624}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Ruffe"], {"csm2" : 3.2, "agi1" : 3.0, "str1" : 1.08, "wil1" : 2.03, "int1" : 0.54}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Saithe"], {"csm2" : 3.2, "agi1" : 3.0, "str1" : 1.35, "wil1" : 1.218, "int1" : 1.218}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Salmon"], {"csm2" : 1.28, "agi1" : 3.0, "str1" : 1.35, "wil1" : 2.03, "csm1" : 3.2}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Tench"], {"csm2" : 3.2, "agi1" : 3.0, "str1" : 0.81, "wil1" : 2.03, "int1" : 0.945}], 
	["Fish in Tears", ["Yellow Onion", "Goatsmilk", "Trout"], {"csm2" : 3.2, "agi1" : 3.0, "str1" : 1.35, "wil1" : 1.421, "dex1" : 1.624}], 
	["Fish in Tears", ["Yellow Onion", "Silver Bream", "Goatsmilk"], {"csm2" : 3.2, "agi1" : 3.675, "str1" : 0.81, "wil1" : 2.093}], 
	["Fishwrap", ["Cave angler", "Blueberries"], {"prc1" : 2.1, "int1" : 3.08, "wil1" : 2.0, "int2" : 2.025}], 
	["Fishwrap", ["Cave angler", "Mulberry"], {"prc1" : 2.1, "int1" : 2.0, "wil1" : 2.0, "int2" : 2.025, "csm1" : 0.945}], 
	["Fishwrap", ["Kvann", "Cave angler", "Blueberries"], {"prc1" : 2.6, "int1" : 2.25, "wil1" : 2.0, "int2" : 1.8}], 
	["Fishwrap", ["Kvann", "Cave angler", "Mulberry"], {"prc1" : 1.4, "int1" : 3.0, "wil1" : 2.0, "int2" : 1.35, "csm1" : 0.63}], 
	["Fishwrap", ["Laurel Leaves", "Cave angler", "Blueberries"], {"prc1" : 2.1, "int1" : 3.08, "wil1" : 2.68, "int2" : 2.025}], 
	["Fishwrap", ["Strawberries", "Cave angler"], {"prc1" : 1.785, "int1" : 3.8, "wil1" : 2.0, "int2" : 2.295}], 
	["Fishwrap", ["Strawberries", "Kvann", "Cave angler"], {"prc1" : 2.66, "int1" : 2.55, "wil1" : 2.0, "int2" : 3.42}], 
	["Greenleaf Pie", ["Green Kelp", "Millet Flour"], {"wil1" : 1.735, "int1" : 2.0, "con1" : 1.68, "csm1" : 0.9}], 
	["Greenleaf Pie", ["Lettuce Leaf", "Millet Flour"], {"wil1" : 3.075, "int1" : 2.0, "con1" : 3.6}], 
	["Grubpie", ["Millet Flour"], {"str2" : 3.0, "prc2" : 3.2, "wil2" : 4.0, "wil1" : 1.4}], 
	["Kebab Meat", ["Adder"], {"con2" : 1.2, "int2" : 1.8}],
	["Kebab Meat", ["Ant"], {"con2" : 0.8, "wil1" : 1.8}],
	["Kebab Meat", ["Badger"], {"con2" : 1.4, "con1" : 1.4}],
	["Kebab Meat", ["Bat"], {"con2" : 1.4, "prc1" : 0.8}],
	["Kebab Meat", ["Bear"], {"con2" : 0.5, "str2" : 3}],
	["Kebab Meat", ["Boar"], {"con2" : 1.3, "con1" : 1.6}],
	["Kebab Meat", ["Chicken"], {"con2" : 1.6, "csm1" : 0.4}],
	["Kebab Meat", ["Fox"], {"con2" : 1.4, "prc1" : 1.2}],
	["Kebab Meat", ["Golden Eagle", "Laurel Leaves"], {"con2" : 0.814, "wil1" : 4.075}], 
	["Kebab Meat", ["Lynx"], {"con2" : 1, "agi1" : 2}],
	["Kebab Meat", ["Mammoth"], {"con2" : 4}],
	["Kebab Meat", ["Moose"], {"con2" : 0.8, "int1" : 2.4}],
	["Kebab Meat", ["Otter"], {"con2" : 1.6, "wil2" : 1}],
	["Kebab Meat", ["Ptarmigan", "Laurel Leaves"], {"str2" : 3.915}], 
	["Kebab Meat", ["Reindeer Venison"], {"con2" : 0.8, "dex1" : 1.8}],
	["Kebab Meat", ["Swan"], {"con2" : 1.2, "prc2" : 1}],
	["Kebab Meat", ["Venison"], {"con2" : 1.4, "prc1" : 1.6}],
	["Kebab Meat", ["Wild Beef"], {"con2" : 0.5, "str1" : 1.5}],
	["Kebab Meat", ["Wildgoat"], {"con2" : 0.5, "wil1" : 1.5}],
	["Lingon Loaf", ["Millet Flour"], {"csm2" : 2.4, "csm1" : 2.0, "con1" : 2.0, "wil1" : 1.05}], 
	["Linseed Loaf", ["Millet Flour"], {"prc1" : 3.2, "con1" : 3.4, "int1" : 1.0}], 
	["Magpie", ["Laurel Leaves", "Millet Flour"], {"int2" : 3.0, "wil1" : 4.0, "con1" : 6.348}], 
	["Magpie", ["Millet Flour", "Chives"], {"int2" : 3.0, "wil1" : 3.2, "con1" : 4.4, "agi1" : 6.2827}], 
	["Magpie", ["Millet Flour", "Kvann"], {"int2" : 3.2, "wil1" : 4.4, "con1" : 3.0}], 
	["Magpie", ["Millet Flour"], {"int2" : 3.0, "wil1" : 3.2, "con1" : 4.4}], 
	["Meatpie", ["Adder", "Millet Flour"], {"str1" : 3.0, "con1" : 5.575, "int2" : 3.6}], 
	["Meatpie", ["Badger", "Millet Flour"], {"str1" : 4.0, "con1" : 4.55, "agi1" : 2.8}], 
	["Meatpie", ["Bat", "Millet Flour"], {"str1" : 4.0, "con1" : 4.55, "int1" : 1.6}], 
	["Meatpie", ["Fox", "Millet Flour"], {"str1" : 4.0, "con1" : 4.55, "int1" : 2.4}], 
	["Meatpie", ["Hedgehog", "Millet Flour"], {"str1" : 4.0, "con1" : 4.95, "con2" : 1.4}],
	["Meatpie", ["Lynx", "Millet Flour"], {"str1" : 2.5, "con1" : 4.0, "int1" : 4.0, "wil1" : 1.75}], 
	["Meatpie", ["Millet Flour", "Bear"], {"str1" : 4.0, "con1" : 10.0625}], 
	["Meatpie", ["Millet Flour", "Boar"], {"str1" : 8.6, "con1" : 3.7375}], 
	["Meatpie", ["Millet Flour", "Venison"], {"str1" : 4.0, "con1" : 4.025, "agi1" : 3.9}], 
	["Meatpie", ["Moose", "Millet Flour"], {"str1" : 2.0, "con1" : 4.0, "int1" : 4.8, "wil1" : 2.1}], 
	["Meatpie", ["Wild Beef", "Millet Flour"], {"str1" : 4.0, "con1" : 5.75}], 
	["Meatpie", ["Wild Horse", "Millet Flour"], {"str1" : 4.0, "con1" : 2.75, "agi1" : 3.0}], 
	["Meatpie", ["Wolf", "Millet Flour"], {"str1" : 6.0, "con1" : 6.625}], 
	["Meatpie", ["Wolverine", "Millet Flour"], {"str1" : 4.0, "con1" : 4.15, "dex2" : 3.2}], 
	["Mushroom & Onion Pirozhki", ["Bay Bolete", "Leek", "Millet Flour"], {"con1" : 3.12, "dex1" : 2.56, "dex2" : 3.0, "int1" : 1.8}], 
	["Mushroom & Onion Pirozhki", ["Bay Bolete", "Red Onion", "Millet Flour"], {"con1" : 3.4, "dex1" : 3.2, "dex2" : 2.4, "str1" : 1.5}], 
	["Mushroom & Onion Pirozhki", ["Bay Bolete", "Yellow Onion", "Millet Flour"], {"con1" : 3.9, "dex1" : 3.2, "dex2" : 3.0}], 
	["Mushroom & Onion Pirozhki", ["Leek", "Millet Flour", "Black Trumpets"], {"con1" : 4.6, "dex1" : 3.2, "prc1" : 1.26, "psy1" : 1.35}], 
	["Mushroom & Onion Pirozhki", ["Leek", "Millet Flour", "Chantrelles"], {"con1" : 4.6, "dex1" : 3.2, "prc1" : 1.08, "agi1" : 0.9}], 
	["Mushroom & Onion Pirozhki", ["Leek", "Millet Flour", "Giant Puffball"], {"con1" : 1.84, "dex1" : 3.2, "prc1" : 4.79}], 
	["Mushroom & Onion Pirozhki", ["Leek", "Millet Flour", "Yellowfeet"], {"con1" : 4.6, "dex1" : 3.2, "prc1" : 1.26, "str1" : 0.9}], 
	["Mushroom & Onion Pirozhki", ["Parasol Mushroom", "Leek", "Millet Flour"], {"con1" : 4.68, "dex1" : 3.84, "int1" : 2.7}], 
	["Mushroom & Onion Pirozhki", ["Parasol Mushroom", "Red Onion", "Millet Flour"], {"con1" : 4.68, "dex1" : 3.84, "int1" : 3.0}], 
	["Mushroom & Onion Pirozhki", ["Parasol Mushroom", "Yellow Onion", "Millet Flour"], {"con1" : 5.85, "dex1" : 4.8}], 
	["Mushroom & Onion Pirozhki", ["Red Onion", "Millet Flour", "Black Trumpets"], {"con1" : 4.6, "dex1" : 3.2, "int1" : 1.4, "psy1" : 1.5}], 
	["Mushroom & Onion Pirozhki", ["Red Onion", "Millet Flour", "Chantrelles"], {"con1" : 4.6, "dex1" : 3.2, "int1" : 1.2, "agi1" : 1.0}], 
	["Mushroom & Onion Pirozhki", ["Red Onion", "Millet Flour", "Giant Puffball"], {"con1" : 1.84, "dex1" : 3.2, "int1" : 2.0, "prc1" : 2.99}], 
	["Mushroom & Onion Pirozhki", ["Red Onion", "Millet Flour", "Yellowfeet"], {"con1" : 4.6, "dex1" : 3.2, "int1" : 1.4, "str1" : 1.0}], 
	["Mushroom & Onion Pirozhki", ["Yellow Onion", "Millet Flour", "Black Trumpets"], {"con1" : 5.75, "dex1" : 2.8, "psy1" : 3.0}], 
	["Mushroom & Onion Pirozhki", ["Yellow Onion", "Millet Flour", "Chantrelles"], {"con1" : 5.75, "dex1" : 2.4, "agi1" : 2.0}], 
	["Mushroom & Onion Pirozhki", ["Yellow Onion", "Millet Flour", "Giant Puffball"], {"con1" : 2.3, "dex1" : 4.0, "prc1" : 3.7375}], 
	["Mushroom & Onion Pirozhki", ["Yellow Onion", "Millet Flour", "Yellowfeet"], {"con1" : 5.75, "dex1" : 2.8, "str1" : 2.0}], 
	["Mushroom-Burst Glutton", ["Adder", "Laurel Leaves", "Bay Bolete"], {"csm2" : 2.16, "prc1" : 1.8, "con1" : 1.5, "int2" : 2.7, "dex2" : 2.25}], 
	["Mushroom-Burst Glutton", ["Adder", "Laurel Leaves", "Chantrelles"], {"csm2" : 2.16, "prc1" : 1.08, "con1" : 3.0, "int2" : 2.7, "agi1" : 0.9}], 
	["Mushroom-Burst Glutton", ["Adder", "Laurel Leaves", "Giant Puffball"], {"csm2" : 2.16, "prc1" : 3.75, "con1" : 1.2, "int2" : 2.7}], 
	["Mushroom-Burst Glutton", ["Adder", "Laurel Leaves", "Yellowfeet"], {"csm2" : 2.16, "prc1" : 1.26, "con1" : 3.0, "int2" : 2.7, "str1" : 0.9}], 
	["Mushroom-Burst Glutton", ["Bat", "Laurel Leaves", "Chantrelles"], {"csm2" : 1.512, "prc1" : 3.0, "con1" : 3.0, "int1" : 0.48, "agi1" : 0.4}], 
	["Mushroom-Burst Glutton", ["Bat", "Laurel Leaves", "Giant Puffball"], {"csm2" : 1.512, "prc1" : 3.15, "con1" : 3.0, "int1" : 0.8}], 
	["Mushroom-Burst Glutton", ["Bat", "Laurel Leaves", "Yellowfeet"], {"csm2" : 1.512, "prc1" : 3.0, "con1" : 3.0, "int1" : 0.56, "str1" : 0.4}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Bay Bolete", "Mallard"], {"csm2" : 2.16, "prc1" : 1.2, "con1" : 3.3, "dex2" : 2.25}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Bay Bolete", "Ptarmigan"], {"csm2" : 2.16, "prc1" : 1.5, "str2" : 3.6, "dex2" : 2.25}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Bay Bolete", "Wood Grouse"], {"csm2" : 2.16, "prc1" : 0.6, "con1" : 3.0, "dex2" : 3.45}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Chantrelles", "Chicken"], {"csm2" : 1.296, "prc1" : 3.0, "con1" : 3.0, "dex1" : 0.864, "csm1" : 0.216}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Chicken", "Giant Puffball"], {"csm2" : 1.728, "prc1" : 3.15, "con1" : 3.0, "dex1" : 0.432}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Chicken", "Yellowfeet"], {"csm2" : 1.728, "prc1" : 3.0, "con1" : 3.0, "str1" : 0.216}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Mallard", "Chantrelles"], {"csm2" : 1.728, "prc1" : 3.0, "con1" : 3.0, "agi1" : 0.216}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Mallard", "Giant Puffball"], {"csm2" : 1.728, "prc1" : 3.15, "con1" : 3.0, "int1" : 0.432}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Mallard", "Yellowfeet"], {"csm2" : 1.728, "prc1" : 3.0, "con1" : 3.0, "str1" : 0.216}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Ptarmigan", "Chantrelles"], {"csm2" : 1.296, "str2" : 3.6, "con1" : 3.0, "dex1" : 1.08}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Ptarmigan", "Giant Puffball"], {"csm2" : 2.16, "str2" : 1.44, "con1" : 3.0, "prc2" : 2.34}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Ptarmigan", "Yellowfeet"], {"csm2" : 1.512, "str2" : 3.6, "con1" : 3.0, "int1" : 1.08}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Seagull", "Chantrelles"], {"csm2" : 2.16, "prc1" : 1.5, "con1" : 3.0, "int1" : 0.36, "agi1" : 0.3}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Seagull", "Giant Puffball"], {"csm2" : 2.16, "prc1" : 3.45, "con1" : 1.2, "int1" : 0.6}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Seagull", "Yellowfeet"], {"csm2" : 2.16, "prc1" : 1.5, "con1" : 3.0, "str1" : 0.3}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Swan", "Bay Bolete"], {"csm2" : 1.296, "prc1" : 1.5, "con1" : 3.0, "int1" : 1.08, "dex2" : 2.25}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Swan", "Chantrelles"], {"csm2" : 1.296, "prc1" : 3.0, "con1" : 3.0, "int1" : 0.648, "agi1" : 0.54}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Swan", "Giant Puffball"], {"csm2" : 1.296, "prc1" : 3.15, "con1" : 3.0, "int1" : 1.08}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Wood Grouse", "Chantrelles"], {"csm2" : 0.5184, "prc1" : 3.0, "con1" : 3.0, "dex2" : 1.728, "dex1" : 0.432}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Wood Grouse", "Giant Puffball"], {"csm2" : 0.864, "prc1" : 3.15, "con1" : 3.0, "dex2" : 1.728}], 
	["Mushroom-Burst Glutton", ["Laurel Leaves", "Wood Grouse", "Yellowfeet"], {"csm2" : 0.6048, "prc1" : 3.0, "con1" : 3.0, "dex2" : 1.728, "int1" : 0.432}], 
	["Mushroom-Burst Glutton", ["Magpie", "Laurel Leaves", "Chantrelles"], {"csm2" : 1.296, "prc1" : 3.0, "con1" : 3.0, "dex1" : 0.15}], 
	["Mushroom-Burst Glutton", ["Magpie", "Laurel Leaves", "Giant Puffball"], {"csm2" : 1.296, "prc1" : 3.15, "con1" : 3.0, "csm1" : 0.3}], 
	["Mushroom-Burst Glutton", ["Magpie", "Laurel Leaves", "Yellowfeet"], {"csm2" : 1.296, "prc1" : 3.0, "con1" : 3.0, "int1" : 0.15}], 
	["Mushroom-Burst Glutton", ["Magpie", "Parasol Mushroom", "Laurel Leaves"], {"csm2" : 0.9, "prc1" : 3.0, "con1" : 3.0, "csm1" : 0.324, "str1" : 0.6}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Adder", "Laurel Leaves"], {"csm2" : 1.5, "prc1" : 1.8, "con1" : 3.0, "str1" : 1.08, "int2" : 2.7}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Laurel Leaves", "Mallard"], {"csm2" : 1.62, "prc1" : 3.0, "con1" : 3.0, "str1" : 0.8, "int1" : 0.2}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Laurel Leaves", "Ptarmigan"], {"csm2" : 1.62, "str2" : 3.6, "con1" : 3.0, "str1" : 1.0}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Laurel Leaves", "Seagull"], {"csm2" : 1.62, "prc1" : 1.5, "con1" : 3.0, "str1" : 1.0, "int1" : 0.6}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Laurel Leaves", "Swan"], {"csm2" : 1.62, "prc1" : 3.0, "con1" : 3.0, "str1" : 0.6, "int1" : 0.5}], 
	["Mushroom-Burst Glutton", ["Parasol Mushroom", "Laurel Leaves", "Wood Grouse"], {"csm2" : 1.62, "prc1" : 3.8, "con1" : 3.0, "str1" : 0.4}],
	["Mushroom-Burst Glutton", ["Swan", "Yellowfeet"], {"csm2" : 1.2, "prc1" : 3.0, "con1" : 3.0, "int1" : 0.7, "str1" : 0.5}], 
	["Olive Bread", ["Millet Flour"], {"str1" : 3.0, "agi2" : 2.0, "dex1" : 3.2, "wil1" : 1.4}], 
	["Pumpkin Bread", ["Millet Flour"], {"csm2" : 2.0, "con1" : 4.6}], 
	["Pumpkin Pie", ["Millet Flour"], {"str1" : 2.0, "con1" : 4.8, "wil1" : 2.1}], 
	["Seedcrisp Flatbread", ["Millet Flour"], {"wil2" : 1.6, "str1" : 1.0, "con1" : 1.7}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Leek", "Beetroot Leaves"], {"str2" : 0.992, "agi1" : 2.0, "csm1" : 2.175, "wil1" : 0.5625, "con1" : 1.35}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Leek", "Lettuce Leaf"], {"str2" : 0.992, "agi1" : 2.0, "csm1" : 1.2, "wil1" : 0.675, "con1" : 3.75}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Lettuce Leaf", "Red Onion"], {"str2" : 0.992, "agi1" : 2.0, "csm1" : 1.5, "wil1" : 0.675, "con1" : 3.9}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Red Onion", "Beetroot Leaves"], {"str2" : 0.992, "agi1" : 2.0, "csm1" : 2.8875, "int1" : 0.2813}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Yellow Onion", "Beetroot Leaves"], {"str2" : 0.7936, "agi1" : 2.0, "csm1" : 3.2214, "wil1" : 0.5625}], 
	["Spicy Salad", ["Turnip", "Laurel Leaves", "Yellow Onion", "Lettuce Leaf"], {"str2" : 0.7936, "agi1" : 2.0, "csm1" : 1.7232, "wil1" : 0.675, "con1" : 3.4464}]
];